### ISSUE TITLE
Slowed down website by 28% in PageSpeed Insights

### ISSUE THREAD

**Issue by rnik12** [snelsi/next-recaptcha-v3#156]
**Describe the bug**
It is bad Idea to include recaptcha js on all pages in nextjs.

Please check the performance before and after:

Before
<img width="1440" alt="Screenshot 2024-01-20 at 9 22 24 AM" src="https://github.com/snelsi/next-recaptcha-v3/assets/6128508/76911c4a-1b33-48d2-94cd-3a08d0dcb59a">

After:
<img width="1440" alt="Screenshot 2024-01-20 at 9 22 33 AM" src="https://github.com/snelsi/next-recaptcha-v3/assets/6128508/1080b27a-d73d-4027-9558-29b90cadc3b6">

Google recommends to load it only when you need forms but I've seen if form changes to another form, recapctha fails to load.

**Comment by snelsi** [comment]
We are using [next/script](https://nextjs.org/docs/app/api-reference/components/script#strategy) to load ReCaptcha.
`ReCaptchaProvider` passes all received props directly to `next/script` component, so you're free to customize it.

By default this script uses `afterInteractive` strategy. 
You can try changing the strategy to `lazyOnload` to improve performance.
This will inject ReCaptcha's script during browser idle time and will load after all resources on the page have been fetched.

Read more about it official Next.js docs:
https://nextjs.org/docs/app/api-reference/components/script#strategy

Alternatively, you can move your `ReCaptchaProvider` component only to pages/components where you use it.
Hopefully, this shouldn't be a problem since Next.js will dedupe all injected scripts.

Otherwise, there's nothing I can do to improve performance of the ReCaptcha's inner logic, sorry.
You can ask for help on the offifcial ReCaptcha repo on Github:
https://github.com/google/recaptcha

Good luck 👍
