### ISSUE TITLE
Allow Cloudflare Turnstile as ReCaptcha replacement

### ISSUE THREAD

**Issue by pegak** [snelsi/next-recaptcha-v3#77]
**Is your feature request related to a problem? Please describe.**
Turnstile has ReCaptcha compatible version. It would be great to allow it as well. It would remove dependency on Google.

**Describe the solution you'd like**
Allow easily use Turnstile via param (same as useEnterprise).

**Describe alternatives you've considered**
I tried passing src manually. But the API is not 1:1 even though the doc says they have compat layer.

**Docs**
https://developers.cloudflare.com/turnstile/get-started/migrating-from-recaptcha/

**Comment by snelsi** [comment]
Hey, thank you for your interest in this library! 👋

I see a couple of problems with your request.

Turnstile's docs that you attached mentions `grecaptcha.render`. Taking a peak into [Turnstile's script](https://challenges.cloudflare.com/turnstile/v0/b5a25e40/api.js?compat=recaptcha), I can see that they add custom `grecaptcha.render` method. But we don't actually use `render` directly anywhere in our code. `render` logic is [embeded directly in the ReCaptcha script's URL](https://developers.google.com/recaptcha/docs/v3#programmatically_invoke_the_challenge).

In theory, you can fix this by manually calling `grecaptcha.render` inside a `useEffect` somewhere in your app:
```tsx
const { grecaptcha, reCaptchaKey } = useReCaptchaContext()

useEffect(() => {
  if (grecaptcha) {
    grecaptcha.render('html_element', {
      'sitekey' :reCaptchaKey
    });
  }
}, [!!grecaptcha, reCaptchaKey])
```

But sadly, it looks like [Turnstile's script](https://challenges.cloudflare.com/turnstile/v0/b5a25e40/api.js?compat=recaptcha) doesn't include `grecaptcha.ready` or `grecaptcha.execute` methods. That's why you probably see errors in your project since we heavily rely on both of these functions in various places.

I don't know much about Turnstile, but for me, it seems like it's not a direct drop-in replacement for ReCaptcha. Or maybe it's compatible, but only with ReCaptcha V2. So I don't feel like including custom attributes/support for this specific case is a good idea.

👉 Maybe, it would make more sense to you to use an appropriate library like [react-turnstile](https://github.com/Le0Developer/react-turnstile) or [@marsidev/react-turnstile](https://github.com/marsidev/react-turnstile). 

Closing this issue for now, but feel free to ask more questions here if you want.

**Comment by pegak** [comment]
Thanks, I found this out too, when digging more. I went for the first mentioned component and it cut more than 300 kB of loaded data. Now I only need Partytown in one of the components or find a time to contribute, but that is currently hard for me. :(
